version: '2.1'

networks:
  default:
  verdaccio_default:
    external: true

services:
  node:
    environment:
      NODE_ENV: development
      npm_config_registry: http://verdaccio:4873
    image: node
    networks:
      - default
      - verdaccio_default
    working_dir: /app
